server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: postgres://frwijxaborehyw:1bbda791e2e4b6dc6dc374d2632be085b4f01272a8eefd7dc876d3bb7c92866f@ec2-52-5-247-46.compute-1.amazonaws.com:5432/d951m5fp86ekoj
    username: frwijxaborehyw
    password: 1bbda791e2e4b6dc6dc374d2632be085b4f01272a8eefd7dc876d3bb7c92866f
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
